name: node-ci-cd

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      DATABASE_URI: ${{ secrets.DATABASE_URI }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 20

      - name: Install dependencies
        run: npm install

      - name: Run Tests
        run: npm test

      - name: Build Docker image
        run: docker build -t fxwizard-image .

      - name: Log in to Docker Hub
        run: docker login -u ${{ secrets.DOCKER_USERNAME }} --password ${{ secrets.DOCKER_PASSWORD }}

      - name: Push Docker Image to Registry
        run: |
          if [ $? -eq 0 ]; then
            docker tag fxwizard-image gijsvdbeuken/fxwizard-image
            docker push gijsvdbeuken/fxwizard-image
          fi

      - name: Deploy to production
        run: |
          # Add your deployment steps here
